language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby-head
gemfile:
  - gemfiles/redis_4.1.gemfile
  - gemfiles/redis_4.2.gemfile
matrix:
  allow_failures:
  - rvm: jruby-head
  - rvm: ruby-head
  exclude:
  - rvm: 2.2
    gemfile: gemfiles/redis_4.2.gemfile
deploy:
  provider: rubygems
  api_key:
    secure: VTosVmCdLWUGK8KyzovYri7ySfd7fACtfL8MClEBBHnI+m2cLCpmtCJ7Z1X7z9BXlj974EDaF8V9iRKzfksXIf8aaPfVQw9AW94fLJZbfSB8YGOGyNbPu9YECoZQB1aZ2lw9s/aEdfwCbmqizO/fYpG3YoPKJdm1ZJpNOFR37Xk=
  gem: redis-rack
  on:
    tags: true
    repo: redis-store/redis-rack
